### ISSUE TITLE
Import python modules

### ISSUE THREAD

**Issue by usernamevalis** [AndersMalmgren/FreePIE#78]
Hello

Is it possible to import external python modules into FreePie?

Thanks

**Comment by AndersMalmgren** [comment]
Yes,  put them in the python lib folder in FreePIE root. The code must work with python 2.7

Also, for somereason our registered globals like oculusvr, keyboard etc are not accessible from these modules

**Comment by usernamevalis** [comment]
Great thanks, I managed to get that working.
Im trying to use pyOSC inside FreePie and have successfully included the module, I can send OSC messages from FreePie to another application.
When I try create a server to receive messages I get the following error :
" 'socket' module has no attribute 'dup' "
Have you encounter this before. or had success receiving OSC messages inside FreePie?

**Comment by AndersMalmgren** [comment]
I know users have used python libs to communicate over TCP atleast, OSC im not sure about

**Comment by AndersMalmgren** [comment]
also, check if your code is 2.7 compliant

**Comment by alx** [comment]
Hi @usernamevalis 

I'm on the same issue, have you solved yours at the time ?

I'm new to python, and from what I could figure out, the dup() issue is related to windows OS (still not sure if it's the case, or how to resolve it).

Thanks and have a nice day,

Alex

**Comment by usernamevalis** [comment]
Hi @alx 

Unfortunately I never resolved the issue. I hope you have better luck.
Let me know if you succeed

Thanks
